// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Newsletter struct {
	ID        int32            `json:"id"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Track struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Mood      string           `json:"mood"`
	AudioUrl  string           `json:"audioUrl"`
	BgUrl     string           `json:"bgUrl"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type User struct {
	Uuid               pgtype.UUID      `json:"uuid"`
	Email              pgtype.Text      `json:"email"`
	PasswordHash       pgtype.Text      `json:"passwordHash"`
	Token              pgtype.Text      `json:"token"`
	TokenLastUpdatedAt pgtype.Timestamp `json:"tokenLastUpdatedAt"`
	IsAdmin            pgtype.Bool      `json:"isAdmin"`
	IsPremium          pgtype.Bool      `json:"isPremium"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
}
