// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletter.sql

package database

import (
	"context"
)

const addNewsletterSubsciber = `-- name: AddNewsletterSubsciber :exec
INSERT INTO newsletter (email)
    VALUES ($1)
`

func (q *Queries) AddNewsletterSubsciber(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, addNewsletterSubsciber, email)
	return err
}

const deleteNewsletterSubscriber = `-- name: DeleteNewsletterSubscriber :exec
DELETE FROM newsletter
WHERE email = $1
`

func (q *Queries) DeleteNewsletterSubscriber(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteNewsletterSubscriber, email)
	return err
}

const getNewsletterSubscriber = `-- name: GetNewsletterSubscriber :one
SELECT
    id, email, created_at
FROM
    newsletter
WHERE
    email = $1
`

func (q *Queries) GetNewsletterSubscriber(ctx context.Context, email string) (Newsletter, error) {
	row := q.db.QueryRow(ctx, getNewsletterSubscriber, email)
	var i Newsletter
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getNewsletterSubscribers = `-- name: GetNewsletterSubscribers :many
SELECT
    id, email, created_at
FROM
    newsletter
`

func (q *Queries) GetNewsletterSubscribers(ctx context.Context) ([]Newsletter, error) {
	rows, err := q.db.Query(ctx, getNewsletterSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Newsletter
	for rows.Next() {
		var i Newsletter
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
