// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package database

import (
	"context"
)

const addTrack = `-- name: AddTrack :exec
INSERT INTO tracks (name, mood, audio_url, bg_url)
    VALUES ($1, $2, $3, $4)
`

type AddTrackParams struct {
	Name     string `json:"name"`
	Mood     string `json:"mood"`
	AudioUrl string `json:"audioUrl"`
	BgUrl    string `json:"bgUrl"`
}

func (q *Queries) AddTrack(ctx context.Context, arg AddTrackParams) error {
	_, err := q.db.Exec(ctx, addTrack,
		arg.Name,
		arg.Mood,
		arg.AudioUrl,
		arg.BgUrl,
	)
	return err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks
WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTrack, id)
	return err
}

const getTrack = `-- name: GetTrack :one
SELECT
    id, name, mood, audio_url, bg_url, created_at
FROM
    tracks
WHERE
    id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id int32) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Mood,
		&i.AudioUrl,
		&i.BgUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getTracks = `-- name: GetTracks :many
SELECT
    id, name, mood, audio_url, bg_url, created_at
FROM
    tracks
`

func (q *Queries) GetTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, getTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mood,
			&i.AudioUrl,
			&i.BgUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrackAudioUrl = `-- name: UpdateTrackAudioUrl :exec
UPDATE
    tracks
SET
    audio_url = $2
WHERE
    id = $1
`

type UpdateTrackAudioUrlParams struct {
	ID       int32  `json:"id"`
	AudioUrl string `json:"audioUrl"`
}

func (q *Queries) UpdateTrackAudioUrl(ctx context.Context, arg UpdateTrackAudioUrlParams) error {
	_, err := q.db.Exec(ctx, updateTrackAudioUrl, arg.ID, arg.AudioUrl)
	return err
}

const updateTrackBgUrl = `-- name: UpdateTrackBgUrl :exec
UPDATE
    tracks
SET
    bg_url = $2
WHERE
    id = $1
`

type UpdateTrackBgUrlParams struct {
	ID    int32  `json:"id"`
	BgUrl string `json:"bgUrl"`
}

func (q *Queries) UpdateTrackBgUrl(ctx context.Context, arg UpdateTrackBgUrlParams) error {
	_, err := q.db.Exec(ctx, updateTrackBgUrl, arg.ID, arg.BgUrl)
	return err
}

const updateTrackMood = `-- name: UpdateTrackMood :exec
UPDATE
    tracks
SET
    mood = $2
WHERE
    id = $1
`

type UpdateTrackMoodParams struct {
	ID   int32  `json:"id"`
	Mood string `json:"mood"`
}

func (q *Queries) UpdateTrackMood(ctx context.Context, arg UpdateTrackMoodParams) error {
	_, err := q.db.Exec(ctx, updateTrackMood, arg.ID, arg.Mood)
	return err
}
