// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users (email, password_hash)
    VALUES ($1, $2)
`

type AddUserParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"passwordHash"`
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.Exec(ctx, addUser, arg.Email, arg.PasswordHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE email = $1
`

func (q *Queries) DeleteUser(ctx context.Context, email pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteUser, email)
	return err
}

const getUser = `-- name: GetUser :one
SELECT
    uuid, email, password_hash, token, token_last_updated_at, is_admin, is_premium, created_at
FROM
    users
WHERE
    email = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.Token,
		&i.TokenLastUpdatedAt,
		&i.IsAdmin,
		&i.IsPremium,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserAccountLevel = `-- name: UpdateUserAccountLevel :exec
UPDATE
    users
SET
    is_admin = $2
WHERE
    uuid = $1
`

type UpdateUserAccountLevelParams struct {
	Uuid    pgtype.UUID `json:"uuid"`
	IsAdmin pgtype.Bool `json:"isAdmin"`
}

func (q *Queries) UpdateUserAccountLevel(ctx context.Context, arg UpdateUserAccountLevelParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountLevel, arg.Uuid, arg.IsAdmin)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE
    users
SET
    email = $2
WHERE
    uuid = $1
`

type UpdateUserEmailParams struct {
	Uuid  pgtype.UUID `json:"uuid"`
	Email pgtype.Text `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Uuid, arg.Email)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE
    users
SET
    password_hash = $2
WHERE
    email = $1
`

type UpdateUserPasswordHashParams struct {
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"passwordHash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.Email, arg.PasswordHash)
	return err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :exec
UPDATE
    users
SET
    is_premium = $2
WHERE
    uuid = $1
`

type UpdateUserSubscriptionParams struct {
	Uuid      pgtype.UUID `json:"uuid"`
	IsPremium pgtype.Bool `json:"isPremium"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateUserSubscription, arg.Uuid, arg.IsPremium)
	return err
}

const updateUserToken = `-- name: UpdateUserToken :exec
UPDATE
    users
SET
    token = $2
WHERE
    uuid = $1
`

type UpdateUserTokenParams struct {
	Uuid  pgtype.UUID `json:"uuid"`
	Token pgtype.Text `json:"token"`
}

func (q *Queries) UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error {
	_, err := q.db.Exec(ctx, updateUserToken, arg.Uuid, arg.Token)
	return err
}
