ARG NODE_VERSION=24-alpine
ARG NGINX_VERSION=1.31-alpine

# Build stage
FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY ./placid-web/package.json ./
RUN npm i
COPY ./placid-web/ .
RUN npm run build

# Stage 2
FROM nginx:${NGINX_VERSION}
COPY nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx --from=builder /app/dist/*/browser /usr/share/nginx/html
EXPOSE 80

CMD [ "nginx","-g", "daemon off;" ]
