ARG NODE_VERSION=24-alpine
ARG NGINX_VERSION=1.31-alpine

# Build stage
FROM node:${NODE_VERSION} AS builder
WORKDIR /app
COPY package.json ./
RUN npm i
COPY . .
RUN npm run build

# Stage 2
FROM nginx:${NGINX_VERSION}
WORKDIR /app
COPY nginx.conf /etc/nginx/nginx.conf
COPY --chown=nginx:nginx --from=builder /app/dist/*/browser /usr/share/nginx/html
# USER nginx
EXPOSE 80

ENTRYPOINT [ "nginx","-c", "/etc/nginx/nginx.conf" ]
CMD [ "-g", "daemon off;" ]
